import { existsSync, readFileSync, writeFileSync } from "node:fs";

/** Result of {@link writeIfChanged}. */
export interface WriteIfChangedResult {
  /**
   * Prior file content, or `null` when the file did not exist — the input
   * for TR4's drift warning (which paths appeared/disappeared).
   */
  previousContent: null | string;
  /**
   * `false` on a byte-identical no-op — the signal `--check` (TR7) and the
   * watch loop (TR5) hang off.
   */
  written: boolean;
}

const HEADER =
  "// Generated by @paramour-js/next. Do not edit — regenerate with `paramour generate`.";

/**
 * Artifact text for a route-path list (TR3): deterministic — sorted, deduped,
 * LF-only, trailing newline, no timestamps. Sorting/deduping happens here as
 * well as in the scanner so byte-identity never depends on who the caller
 * was. Always the leading-pipe multiline union form, even for one path — one
 * shape, no count-dependent formatting.
 */
export function emitArtifact(paths: readonly string[]): string {
  const sorted = [...new Set(paths)].sort();
  if (sorted.length === 0) {
    // TR3: no routes yet → NO `routes` member (explicitly not `never`, which
    // would make every `defineRoute` call an error). The empty merge keeps
    // the documented world-A `string` fallback (RL8).
    return [
      HEADER,
      'import "paramour";',
      "",
      'declare module "paramour" {',
      "  // TR3: empty merge — no routes discovered yet; the pre-generation",
      "  // `string` fallback stays in effect.",
      "  // eslint-disable-next-line @typescript-eslint/no-empty-object-type",
      "  interface ParamourRegister {}",
      "}",
      "",
    ].join("\n");
  }
  // The union's closing `;` attaches to the last member line.
  const union = `${sorted.map((path) => `      | "${path}"`).join("\n")};`;
  return [
    HEADER,
    'import "paramour";',
    "",
    'declare module "paramour" {',
    "  interface ParamourRegister {",
    "    routes:",
    union,
    "  }",
    "}",
    "",
  ].join("\n");
}

/**
 * Compare-before-write (TR3): a no-op regeneration must not touch the file —
 * that property is what prevents TS-server churn, watch-loop feedback, and
 * concurrent-generator races (TR6).
 */
export function writeIfChanged(
  filePath: string,
  content: string,
): WriteIfChangedResult {
  const previousContent = existsSync(filePath)
    ? readFileSync(filePath, "utf8")
    : null;
  if (previousContent === content) return { previousContent, written: false };
  writeFileSync(filePath, content);
  return { previousContent, written: true };
}
