import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";

/** Result of {@link writeIfChanged}. */
export interface WriteIfChangedResult {
  /**
   * Prior file content, or `null` when the file did not exist — the input
   * for TR4's drift warning (which paths appeared/disappeared).
   */
  previousContent: null | string;
  /**
   * `false` on a byte-identical no-op — the signal `--check` (TR7) and the
   * watch loop (TR5) hang off.
   */
  written: boolean;
}

const HEADER =
  "// Generated by @paramour-js/next. Do not edit — regenerate with `paramour generate`.";

/** Input of {@link emitArtifact} — one union per router (PR9). */
export interface EmitRoutes {
  appRoutes: readonly string[];
  pagesRoutes: readonly string[];
}

/**
 * Artifact text for the per-router route unions (TR3/PR9): deterministic —
 * sorted, deduped, LF-only, trailing newline, no timestamps. Sorting/deduping
 * happens here as well as in the scanner so byte-identity never depends on
 * who the caller was. Always the leading-pipe multiline union form, even for
 * one path — one shape, no count-dependent formatting. An empty union omits
 * its member entirely (TR3's absent-not-`never` rule, applied per router in
 * PR9): a pages-only project keeps world-A's permissive `string` fallback
 * for `defineAppRoute`, and vice versa.
 */
export function emitArtifact(routes: EmitRoutes): string {
  const members = (["appRoutes", "pagesRoutes"] as const).flatMap((member) => {
    const sorted = [...new Set(routes[member])].sort();
    if (sorted.length === 0) return [];
    // The union's closing `;` attaches to the last member line. Paths go
    // through JSON.stringify, not raw `"${path}"`: a dirname may legally
    // contain a quote or backslash (Linux/macOS), which unescaped would emit
    // invalid TS or silently declare the wrong route. JSON string escaping is
    // a subset of TS string-literal escaping (output stays valid TS) and is
    // deterministic, so TR3's byte-identity guarantee holds.
    return [
      `    ${member}:`,
      `${sorted.map((path) => `      | ${JSON.stringify(path)}`).join("\n")};`,
    ];
  });
  if (members.length === 0) {
    // TR3: no routes yet → NO members (explicitly not `never`, which would
    // make every route-constructor call an error). The empty merge keeps
    // the documented world-A `string` fallback (RL8).
    return [
      HEADER,
      'import "paramour";',
      "",
      'declare module "paramour" {',
      "  // TR3: empty merge — no routes discovered yet; the pre-generation",
      "  // `string` fallback stays in effect.",
      "  // eslint-disable-next-line @typescript-eslint/no-empty-object-type",
      "  interface ParamourRegister {}",
      "}",
      "",
    ].join("\n");
  }
  return [
    HEADER,
    'import "paramour";',
    "",
    'declare module "paramour" {',
    "  interface ParamourRegister {",
    ...members,
    "  }",
    "}",
    "",
  ].join("\n");
}

/**
 * Compare-before-write (TR3): a no-op regeneration must not touch the file —
 * that property is what prevents TS-server churn, watch-loop feedback, and
 * concurrent-generator races (TR6).
 */
export function writeIfChanged(
  filePath: string,
  content: string,
): WriteIfChangedResult {
  const previousContent = existsSync(filePath)
    ? readFileSync(filePath, "utf8")
    : null;
  if (previousContent === content) return { previousContent, written: false };
  // TR3's outFile escape hatch may point into a not-yet-existing directory.
  mkdirSync(dirname(filePath), { recursive: true });
  writeFileSync(filePath, content);
  return { previousContent, written: true };
}
