import { existsSync, readFileSync, statSync } from "node:fs";
import { join } from "node:path";
import { setTimeout as sleep } from "node:timers/promises";
import { describe, expect, it } from "vitest";

import { emitArtifact, writeIfChanged } from "../src";
import { makeTempDir } from "./helpers.js";

/** App-only emission — the shape most existing suites exercise. */
function emitApp(appRoutes: readonly string[]): string {
  return emitArtifact({ appRoutes, pagesRoutes: [] });
}

describe("emitArtifact (TR3/PR9)", () => {
  it("emits the exact artifact bytes for a hybrid project", () => {
    const expected = `// Generated by @paramour-js/next. Do not edit — regenerate with \`paramour generate\`.
import "paramour";

declare module "paramour" {
  interface ParamourRegister {
    appRoutes:
      | "/"
      | "/product/[id]";
    pagesRoutes:
      | "/legacy"
      | "/legacy/[id]";
  }
}
`;
    expect(
      emitArtifact({
        appRoutes: ["/", "/product/[id]"],
        pagesRoutes: ["/legacy", "/legacy/[id]"],
      }),
    ).toBe(expected);
  });

  it("omits pagesRoutes for an app-only project (absent, not never — TR3/PR9)", () => {
    const content = emitApp(["/", "/about"]);
    expect(content).toContain("appRoutes:");
    expect(content).not.toContain("pagesRoutes");
    expect(content).not.toContain("never");
  });

  it("omits appRoutes for a pages-only project (absent, not never — TR3/PR9)", () => {
    const content = emitArtifact({ appRoutes: [], pagesRoutes: ["/legacy"] });
    expect(content).toContain("pagesRoutes:");
    expect(content).not.toContain("appRoutes");
    expect(content).not.toContain("never");
  });

  it("keeps the leading-pipe union form for a single path", () => {
    expect(emitApp(["/"])).toContain('appRoutes:\n      | "/";');
  });

  it("is deterministic and sorts/dedupes its own input", () => {
    const canonical = emitApp(["/a", "/b"]);
    expect(emitApp(["/a", "/b"])).toBe(canonical);
    expect(emitApp(["/b", "/a", "/a"])).toBe(canonical);
  });

  it("uses LF endings and one trailing newline on every OS", () => {
    const content = emitArtifact({ appRoutes: ["/a"], pagesRoutes: ["/b"] });
    expect(content).not.toContain("\r");
    expect(content.endsWith("\n")).toBe(true);
    expect(content.endsWith("\n\n")).toBe(false);
  });

  it("sorts by code unit, not locale ('/Z' < '/a' < '/é')", () => {
    // A localeCompare regression would pass every ASCII-lowercase-only test;
    // this pin feeds TR3's byte-identical-on-every-OS guarantee.
    expect(emitApp(["/a", "/Z", "/é"])).toContain(
      ['      | "/Z"', '      | "/a"', '      | "/é";'].join("\n"),
    );
  });

  it("emits the empty merge when both scans are empty", () => {
    const content = emitArtifact({ appRoutes: [], pagesRoutes: [] });
    expect(content).toContain("interface ParamourRegister {}");
    expect(content).not.toContain("Routes:");
    expect(content).not.toContain("never");
  });

  it("escapes quotes and backslashes into valid TS string literals (bug 7)", () => {
    // Legal POSIX dirnames may contain " or \; interpolated raw they'd emit a
    // TS syntax error (broken quote) or a spurious escape (\b = backspace).
    // Each emitted literal is valid JSON, hence valid TS, and round-trips to
    // the original path.
    for (const path of ['/a"b', "/a\\b", "/c\\td"]) {
      const line = emitApp([path])
        .split("\n")
        .find((l) => l.trimStart().startsWith("|"));
      expect(line).toBeDefined();
      // Drop the leading `| ` and the union's trailing `;` on the last member.
      const literal = (line ?? "")
        .trim()
        .replace(/^\|\s*/, "")
        .replace(/;$/, "");
      expect(JSON.parse(literal)).toBe(path);
    }
  });

  it("pins the exact escaped bytes for a quote and a backslash (bug 7)", () => {
    expect(emitApp(['/a"b'])).toContain('| "/a\\"b"');
    expect(emitApp(["/a\\b"])).toContain('| "/a\\\\b"');
  });

  it("emits byte-identical output for an ordinary path (no regression)", () => {
    // The common case must be unchanged by the JSON.stringify escaping.
    expect(emitApp(["/product/[id]"])).toContain('| "/product/[id]"');
  });
});

describe("writeIfChanged (TR3)", () => {
  it("creates a missing file and reports it wrote", () => {
    const file = join(makeTempDir(), "paramour-env.d.ts");
    expect(writeIfChanged(file, "content\n")).toEqual({
      previousContent: null,
      written: true,
    });
    expect(readFileSync(file, "utf8")).toBe("content\n");
  });

  it("leaves an identical file untouched", async () => {
    const file = join(makeTempDir(), "paramour-env.d.ts");
    writeIfChanged(file, "content\n");
    // The sleep guarantees a real rewrite WOULD have bumped mtime.
    await sleep(25);
    const mtimeBefore = statSync(file).mtimeMs;
    expect(writeIfChanged(file, "content\n")).toEqual({
      previousContent: "content\n",
      written: false,
    });
    expect(statSync(file).mtimeMs).toBe(mtimeBefore);
  });

  it("rewrites a changed file and returns the prior content", () => {
    const file = join(makeTempDir(), "paramour-env.d.ts");
    writeIfChanged(file, "old\n");
    expect(writeIfChanged(file, "new\n")).toEqual({
      previousContent: "old\n",
      written: true,
    });
    expect(readFileSync(file, "utf8")).toBe("new\n");
  });

  it("creates missing nested parent directories for the target file", () => {
    const file = join(makeTempDir(), "types", "deep", "routes.d.ts");
    expect(writeIfChanged(file, "content\n")).toEqual({
      previousContent: null,
      written: true,
    });
    expect(readFileSync(file, "utf8")).toBe("content\n");
  });

  it("distinguishes an empty existing file from a missing one", () => {
    const file = join(makeTempDir(), "paramour-env.d.ts");
    writeIfChanged(file, "");
    expect(existsSync(file)).toBe(true);
    expect(writeIfChanged(file, "")).toEqual({
      previousContent: "",
      written: false,
    });
  });
});
