// Generated by @paramour-js/next. Do not edit — regenerate with `paramour generate`.
import "paramour";

declare module "paramour" {
  interface ParamourRegister {
    routes:
      | "/"
      | "/docs/[[...slug]]"
      | "/events/[date]"
      | "/files/[...path]"
      | "/find"
      | "/products/[id]"
      | "/serialize";
  }
}
