// Generated by @paramour-js/next. Do not edit — regenerate with `paramour generate`.
import "paramour";

declare module "paramour" {
  interface ParamourRegister {
    appRoutes:
      | "/"
      | "/_internal"
      | "/about"
      | "/dashboard"
      | "/docs/[[...slug]]"
      | "/events/[date]"
      | "/feed"
      | "/files/[...path]"
      | "/find"
      | "/gallery"
      | "/gallery/[photoId]"
      | "/products"
      | "/products/[id]"
      | "/search"
      | "/serialize";
    pagesRoutes:
      | "/legacy";
  }
}
