// Generated by @paramour-js/next. Do not edit — regenerate with `paramour generate`.
import "paramour";

declare module "paramour" {
  interface ParamourRegister {
    appRoutes:
      | "/"
      | "/docs/[[...slug]]"
      | "/product/[id]";
  }
}
